/* generated by Svelte v3.32.1 */
"use strict";

const { create_ssr_component, escape, spread } = require("svelte/internal");

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<a${spread([
		{
			target: escape(true ? undefined : "_blank")
		},
		$$props
	])}>Hello, world!
</a>`;
});

exports.default = Component;
